### ISSUE TITLE
Clase Abstracta - GestorArchivos

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#11]
Convertir el GestorCsv en una clase abstracta GestorArchivos y plantear sus clases hijas:
 ->GestorCsv, GestorTxt, GestorJSON

**Comment by MMA2004** [comment]
Clase abstracta Gestor Archivos creada y clases hijas adaptadas
