### ISSUE TITLE
Generalizacion de las columnas a buscar - GestorArchivos

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#12]
** Resolver antes:
- https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/11**

Plantear el diseño de los Gestor de Archivos para que reciban como parámetros las etiquetas de las columnas que necesitan buscar, la ruta de los archivos y los codigos snies a buscar. Tener en cuenta que tambien hay que diseñar el leerProgramas() para obtener dichos codigos snies.

**Comment by MMA2004** [comment]
Ya se adaptaron las funciones de las clases para que reciban los parámetros requeridos para la nueva implementación. Falta hacer la implementación de esas funciones.
