### ISSUE TITLE
Delimitador Variable - GestorArchivos

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#13]
** Resolver antes: 
- https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/12**

Permitir que las clases tipo GestorArchivos puedan utilizar cualquier delimitador
Ej: En el proyecto 1, siempre era el ";" de los csv, y eso se dejó constante en el código
,la idea sería hacer que eso fuera una variable

**Comment by MMA2004** [comment]
Para solucionar esto se creo un archivo de contantes en el cual irán todas las cadenas quemadas del código incluyendo el delimitador de los archivos lo cual hará que sea muy sencillo de cambiar si se necesita.
