### ISSUE TITLE
Implementar GestorCsv

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#16]
Implementacion completa de la clase hija GestorCsv.

Para las comparaciones entre nombres de etiquetas dadas y etiquetas del archivo, utilizar la clase Utilidad para poder hacer en minusculas y sin espacios las comparaciones.

Formato del vector<vector<string>> que se necesita devolver:

[
["Codigo Snies", "Nombre Programa", ..., "Inscritos", "Sexo", "Ano"]               #Nombres columnas
["1", "Ing Sis", ... ,"456", "Hombre", "2022" ]
]

**Comment by MMA2004** [comment]
Ya se hizo la implementación de de GestorCSV para que este pueda hacer la búsqueda de los programas académicos mas generalizada

**Comment by juanpnaranjo2006** [comment]
Faltaban los metodos de crear Archivos ;c

**Comment by MMA2004** [comment]
Ya se implementaron las funciones de creación de los archivos de salida
