### ISSUE TITLE
Implementacion GestorJSON

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#18]
Implementacion completa de la clase hija GestorJSON.

**Investigar como funcionan los archivos JSON para lectura y escritura de archivos**

Para las comparaciones entre nombres de etiquetas dadas y etiquetas del archivo, utilizar la clase Utilidad para poder hacer en minusculas y sin espacios las comparaciones.

Formato del vector<vector<string>> que se necesita devolver:

[
["Codigo Snies", "Nombre Programa", ..., "Inscritos", "Sexo", "Ano"]               #Nombres columnas
["1", "Ing Sis", ... ,"456", "Hombre", "2022" ]
]

**Comment by zulu27** [comment]
Ya se realizo toda la implementación correspondiente al GestorJson, revisar la rama Gestorjson
