### ISSUE TITLE
buscarProgramas()

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#28]
**Resolver antes:
- https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/26
**

Adaptar el método buscarProgramas() del Controlador al nuevo diseño

**Comment by zulu27** [comment]
Ya se adapto y se resolvio el issue esta en SNIESController
