### ISSUE TITLE
Mapa de Atributos - programaAcademico

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#3]
Hacer que las clases programaAcademico tenga un mapa con sus atributos donde la llave sea el nombre del atributo.

Se pide que por favor el nombre del atributo quede guardado con minusculas y sin espacios para evitar problemas de formato

**Comment by zulu27** [comment]
Ya se hicieron los cambios, están en la rama Cesar
