### ISSUE TITLE
Consulta Atributos - programaAcademico

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#4]
**Resolver Primero: https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/3**

Permitir consultar un atributo especifico del programaAcademico mediante el mapa

**Comment by zulu27** [comment]
Ya se agrego la consulta por medio de los mapas utilizando la clave, todo se encuentra en la rama Cesar
