### ISSUE TITLE
Mapa Atributos - Consolidado

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#5]
Hacer que la clase consolidado tenga un mapa con sus atributos donde la llave sea el nombre del atributo

**Comment by zulu27** [comment]
Ya se hizo el cambio a mapas en consolidado, quedaron dos mapas uno con dato int y otro con dato string(ver rama Cesar)
