### ISSUE TITLE
Consulta Atributos - Consolidados

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#6]
**Resolver antes: https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/5**

Permitir consultar un atributo especifico del consolidado mediante el mapa

**Comment by zulu27** [comment]
ya se hizo, esta en la rama Cesar
