### ISSUE TITLE
Relacion ProgramaAcademico -> Consolidado

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#7]
**Resolver antes: 
-https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/4
-https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/6**

Hacer que la relación programaAcademico -> consolidado no sea mediante un vector sino mediante un mapa.

Donde la llave se manejaria con este estilo

Ejemplo:
"Mujeres" "2022" "1"
string("mujeres-2022-1")
consolidados[string]

**Comment by zulu27** [comment]
hecho, esta en rama César tambien se tuvo que cambiar el destructor
