### ISSUE TITLE
Busqueda de Informacion - programaAcademico

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error#8]
**Resolver antes:
-https://github.com/300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-sintax-error/issues/7**

Permitir mediante metodos publicos que se pueda iterar sobre los consolidados de un programa
academico segun solo el genero, o el año, o el semestre (1 o 2), o cualquier combinacion de estas.
El objetivo es devolver todos los consolidados que cumplan los criterios de busqueda.

**Comment by zulu27** [comment]
Ya esta en rama César, la parte de iterar sobre los consolidados para obtener varios consolidados que cumplan con una misma característica se la vamos a dejar al controlador
